app = "huntbot"
primary_region = "ord"

[http_service]
  force_https = true
  auto_start_machines = false

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  timeout = "5s"
  method = "GET"
  path = "/"

[[mounts]]
  source = "state"
  destination = "/state"
