// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/emojihunt/emojihunt/state/status"
)

type Changelog struct {
	ID     int64           `json:"id"`
	Kind   status.AblyKind `json:"kind"`
	Puzzle []byte          `json:"puzzle"`
	Round  []byte          `json:"round"`
}

type DiscoveredPuzzle struct {
	ID              int64         `json:"id"`
	PuzzleURL       string        `json:"puzzle_url"`
	Name            string        `json:"name"`
	DiscoveredRound sql.NullInt64 `json:"discovered_round"`
}

type DiscoveredRound struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	MessageID  string    `json:"message_id"`
	NotifiedAt time.Time `json:"notified_at"`
	CreatedAs  int64     `json:"created_as"`
}

type Puzzle struct {
	ID             int64         `json:"id"`
	Name           string        `json:"name"`
	Answer         string        `json:"answer"`
	Round          int64         `json:"round"`
	Status         status.Status `json:"status"`
	Note           string        `json:"note"`
	Location       string        `json:"location"`
	PuzzleURL      string        `json:"puzzle_url"`
	SpreadsheetID  string        `json:"spreadsheet_id"`
	DiscordChannel string        `json:"discord_channel"`
	Meta           bool          `json:"meta"`
	VoiceRoom      string        `json:"voice_room"`
	Reminder       time.Time     `json:"reminder"`
}

type Round struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	Emoji           string `json:"emoji"`
	Hue             int64  `json:"hue"`
	Sort            int64  `json:"sort"`
	Special         bool   `json:"special"`
	DriveFolder     string `json:"drive_folder"`
	DiscordCategory string `json:"discord_category"`
}

type Setting struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}
